### ISSUE TITLE
Self hosted solution not working

### ISSUE THREAD

**Issue by dprokhorov17** [lmnr-ai/lmnr#516]
Firstly, after an email is being entered, the onboarding site can't opened.

After the reload, I can't create a new workspace:

<img width="351" alt="Image" src="https://github.com/user-attachments/assets/27e1d356-df52-4c0b-ae66-aa8ee1c6daca" />

The workspace is empty and the Create button is greyed out.

**Comment by skull8888888** [comment]
@dprokhorov17 we've released a new version 10mins ago, do you have the latest images?

**Comment by dinmukhamedm** [comment]
@dprokhorov17 if you do `docker-compose` down and `docker-compose up` again, it must pull the newest images (If not, you may need to `docker system prune`. Also output of `docker image ls` will be helpful to us. If the newest image fixes this, feel free to close the issue. If not, I'll investigate. Please let us know

**Comment by dprokhorov17** [comment]
@dinmukhamedm @skull8888888 Is still not working... Here is the image ls:

```
ghcr.io/lmnr-ai/app-server          latest    37ce1650418d   37 minutes ago   151MB
ghcr.io/lmnr-ai/frontend            latest    354c1f63f90c   44 minutes ago   268MB
ghcr.io/lmnr-ai/agent-manager       latest    2f085aade7a7   47 minutes ago   415MB
```

**Comment by dinmukhamedm** [comment]
@dprokhorov17 thanks for the report. I will investigate and release a fix ASAP. As a temporary workaround, please update your docker-compose.yml with the following:

```
  app-server:
    image: ghcr.io/lmnr-ai/app-server:0.1.4-alpha.0
    pull_policy: always

  agent-manager:
    image: ghcr.io/lmnr-ai/agent-manager:0.1.4-alpha.0
    pull_policy: always

  frontend:
    image: ghcr.io/lmnr-ai/frontend:0.1.4-alpha.0
    pull_policy: always
```

If `0.1.4-alpha.0` doesn't help, the latest stable release was `v0.1.3` (note the v). I'll update on this issue, once fixed

**Comment by dinmukhamedm** [comment]
I did a fresh clean install from `main`, and things work for me. Looking at the symptoms you've described, I am assuming, some of the cookies or auth state got messed up.

Can you try the following:
1. `git reset --hard main && git pull` just in case.
2. Manually navigate to `localhost:5667/onboarding` (the port may be different due to your configuration). You must see the onboarding flow again, create the project here. If that doesn't work, continue with the steps below
3. If the page breaks -> clear your browser cookies for localhost:5667 (all, not just session) and refresh the page. If things work, nice. Otherwise continue with the steps below.
4. If that doesn't help, simply try a different email for log in.
5. If that is not an option, we will have to clear your DB. I am assuming you don't have any [valuable] data there yet. For this, first check the volume name

```
docker volume ls
```

you must see something like `lmnr_postgres-data`. Take a note of this

```
docker compose down
docker volume rm lmnr_postgres-data
```

And then restart with `docker compose up`.

One of these 5 steps must certainly fix the issue for you.

Let us know if this helps @dprokhorov17

**Comment by dprokhorov17** [comment]
Hi @dinmukhamedm ,

`clear your browser cookies for localhost:5667` -> jap, that worked 👍 

Btw, are you guys planning to support LangFlow?
